name: Generate Snake Animation

on:
  schedule:
    # Runs at 12:00 AM every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snk
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#8BC34A,#4CAF50,#388E3C,#1B5E20

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/"
          commit: "--allow-empty"
          push: true